version: "3"

services:
  batch:
    container_name: batch
    image: kooose/ml-system-in-actions:batch_0.0.1
    restart: always
    environment:
      - PLATFORM=docker_compose
      - QUEUE_NAME=queue
      - LABEL_FILEPATH=/batch/models/labels.json
      # - SERVICE_TRANSFORMERS=http://localhost:7001/v1/models/transformers_imdb/versions/3:predict
      - SERVICE_BERT=http://localhost:7002/v1/models/bert_imdb/versions/3:predict
    entrypoint:
      ["python", "-m", "src.backend.prediction_batch.py"]
    depends_on:
      - redis
      - bert
      # - transformers

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"