version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db/data:/var/lib/mysql
      - ./mysql/db/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=log_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    hostname: mysql
    restart: always
    stdin_open: true